config/routes.rb
Rails.application.routes.draw do
  resources :enrolls
  resources :courses
  resources :students
  resources :people
  resources :things
  resources :widgets

  root 'welcome#index'

end

app/models/enroll.rb
class Enroll < ActiveRecord::Base
  belongs_to :course, primary_key: "course_id"
  belongs_to :student, primary_key: "student_id"
end

app/controllers/enrolls_controller.rb
class EnrollsController < ApplicationController
  before_action :set_enroll, only: [:show, :edit, :update, :destroy]

  # GET /enrolls
  # GET /enrolls.json
  def index
    @enrolls = Enroll.all
  end

  # GET /enrolls/1
  # GET /enrolls/1.json
  def show
  end

  # GET /enrolls/new
  def new
    @enroll = Enroll.new
  end

  # GET /enrolls/1/edit
  def edit
  end

  # POST /enrolls
  # POST /enrolls.json
  def create
    @enroll = Enroll.new(enroll_params)

    respond_to do |format|
      if @enroll.save
        format.html { redirect_to @enroll, notice: 'Enroll was successfully created.' }
        format.json { render :show, status: :created, location: @enroll }
      else
        format.html { render :new }
        format.json { render json: @enroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrolls/1
  # PATCH/PUT /enrolls/1.json
  def update
    respond_to do |format|
      if @enroll.update(enroll_params)
        format.html { redirect_to @enroll, notice: 'Enroll was successfully updated.' }
        format.json { render :show, status: :ok, location: @enroll }
      else
        format.html { render :edit }
        format.json { render json: @enroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrolls/1
  # DELETE /enrolls/1.json
  def destroy
    @enroll.destroy
    respond_to do |format|
      format.html { redirect_to enrolls_url, notice: 'Enroll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enroll
      @enroll = Enroll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enroll_params
      params.require(:enroll).permit(:student_id, :course_id, :percentage, :lettergrade)
    end
end

app/helpers/enrolls_helper.rb
module EnrollsHelper
end

app/views/enrolls/_form.html.erb
<%= form_for(@enroll) do |f| %>
  <% if @enroll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enroll.errors.count, "error") %> prohibited this enroll from being saved:</h2>

      <ul>
      <% @enroll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :percentage %><br>
    <%= f.text_field :percentage %>
  </div>
  <div class="field">
    <%= f.label :lettergrade %><br>
    <%= f.text_field :lettergrade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enrolls/edit.html.erb
<h1>Editing Enroll</h1>

<%= render 'form' %>

<%= link_to 'Show', @enroll %> |
<%= link_to 'Back', enrolls_path %>

app/views/enrolls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Enrolls</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Course</th>
      <th>Percentage</th>
      <th>Lettergrade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrolls.each do |enroll| %>
      <tr>
        <td><%= enroll.student_id %></td>
        <td><%= enroll.course_id %></td>
        <td><%= enroll.percentage %></td>
        <td><%= enroll.lettergrade %></td>
        <td><%= link_to 'Show', enroll %></td>
        <td><%= link_to 'Edit', edit_enroll_path(enroll) %></td>
        <td><%= link_to 'Destroy', enroll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enroll', new_enroll_path %>

app/views/enrolls/new.html.erb
<h1>New Enroll</h1>

<%= render 'form' %>

<%= link_to 'Back', enrolls_path %>

app/views/enrolls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @enroll.student_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @enroll.course_id %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @enroll.percentage %>
</p>

<p>
  <strong>Lettergrade:</strong>
  <%= @enroll.lettergrade %>
</p>

<%= link_to 'Edit', edit_enroll_path(@enroll) %> |
<%= link_to 'Back', enrolls_path %>